### ISSUE TITLE
Skip docker requirement by overriding input

### ISSUE THREAD

**Issue by Welliton309** [openwdl/wdl#317] opened 2019-06-11 13:13 UTC
It has been great to work with WDL + Docker images. However sometimes we need to scale genomics data processing by submitting to a cluster and this kind of computing environment doesn't work well with Docker because it requires root access. I also tried to use udocker but it takes long time to start containers and sometimes stop working (tested with Broad Docker images).

I would like to propose a way to skip Docker requirement in tasks and leaving the responsibility of installing required software locally to the user. This would help us to use Cromwell+WDL in cluster environments. Here is a example:

```wdl
version 1.0

task DockerOverride {
    input {
        String name = "Docker"
        String output_file_name = "hello.txt"
        String docker = "ubuntu:bionic"
    }

    command {
        echo "Hello, ~{name}!" > ~{output_file_name}
    }

    output {
        File output_file = output_file_name
    }

    runtime {
        docker: docker
    }
}

workflow Wf {
    call DockerOverride {

    }
}
```

Set docker to `null` to skip Docker requirement.

```json
{
  "Wf.DockerOverride.name": "Cluster",
  "Wf.DockerOverride.docker": null
}
```

**Comment by DavyCats** [comment] 2019-06-11 14:19
Cromwell will ignore any runtime attributes not specified in the backend configuration. If you want to run without docker, you can simply omit the `docker` runtime attribute in this configuration, like was done in [this example](https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/SGE.conf#L31). You won't need to change your WDL files or override the image with `null`.

Alternatively, you may want to look into [singularity](https://www.sylabs.io/guides/3.2/user-guide/), which will allow you to run docker images without root access. This is what we are using on our SGE cluster.

**Comment by Welliton309** [comment] 2019-06-11 14:23
Thank you @DavyCats I will fix my Cromwell conf. Singularity is a great solution, I will try to convince the cluster admin to install it.

**Comment by geoffjentry** [comment] 2019-06-11 15:11
@Welliton309 As @DavyCats mentioned - for Cromwell there are already things one can try.

From a pure WDL perspective there's the combination of #313 and #315, both of which should provide what you're looking for once they merge in. If you'd like to help guide their development please do comment over there.

Will close this issue as an effective duplicate of those PRs

**Closed by geoffjentry** 2019-06-11 15:11 UTC
