### ISSUE TITLE
Encapsulate sets of inputs

### ISSUE THREAD

**Issue by davidbenjamin** [openwdl/wdl#102] opened 2017-04-09 06:20 UTC
For Mutect we use a lot of sub-workflows, and it's tedious to pass a large set of parameters repeatedly.  For example:

```java
import "single_sample.wdl" as SingleSample
workflow MultiSample {
  #these are the parameters of the single-sample subworkflow
  File param1
  File param2
  . . .
  Int param20

  #other parameters

  scatter (sample in samples) {
    call SingleSample.single_sample {
      input:
        File param1
        File param2
        . . .
       Int param20
    }
  }
}
```
In this case, the same list of parameters is copied 5 times: the single-sample task inputs, the single-sample workflow inputs, the single-sample workflow's call to the task, the multi-sample workflow inputs, and the multi-sample workflow's call to the single-sample workflow.  It would be really nice to be able to encapsulate all these parameters, eg

```java
params MyParams {
  File param1
  File param2
  . . .
  Int param20
}

task MyTask {
  MyParams params

  command {
    java -jar ${params.gatk} -R ${params.reference} -L ${params.intervals} . . .
  }
}

workflow MyWorkflow {
  MyParams params

  call MyTask { input params = params }
}
```

**Comment by cjllanwarne** [comment] 2018-01-08 18:28
This looks like a +1 for the struct PR to me: https://github.com/openwdl/wdl/pull/160

**Comment by patmagee** [comment] 2018-01-12 12:19
closing this as a duplicate of  #160

**Closed by patmagee** 2018-01-12 12:19 UTC
Labels: enhancement
