### ISSUE TITLE
Mapping inputs for sub-workflow calls

### ISSUE THREAD

**Issue by wdesouza** [openwdl/wdl#217] opened 2018-06-01 12:24 UTC
Is it possible to map inputs for calls inside a sub-workflow? Example:

subworkflow.wdl:

```wdl
task A {
  String message

  command {
    echo ${message}
  }

  output {
    File messageFile = stdout()
  }
}

workflow B {
  call A

  output {
    File outputFile = A.messageFile
  }
}
```

```wdl
import "subworkflow.wdl" as sub

workflow C {
  call sub.B {
    input:
      A.message = "Hello, World!"
  }

  output {
    Array[String] message = read_lines(B.outputFile)
  }
}
```

WOMtool validation raises error:

```
ERROR: Unexpected symbol (line 6, col 8) when parsing 'mapping'.

Expected equal, got ..

      A.message = "Hello, World!"
       ^

$mapping = :identifier :equal $e -> IOMapping( key=$0, value=$2 )
```

In real world scenario, I am trying to iterate over samples calling [GATK Best Practices for Data Pre-Processing](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl). I would like to map values to call inputs of this workflow. For example, set genome index and dictionary files created by previous calls instead of setting manually in inputs JSON file.

**Comment by patmagee** [comment] 2018-06-01 13:17
@Welliton309 Try explicitly naming the inputs in the subworkflow which you want to call, instead of only naming them in the task. I do not think you can use a `.` in a input notation according to the existing grammar. 

so change you workflow `B` to:
```wdl
workflow B {
  String message
  call A {
    input: 
      message = message
  }

  output {
    File outputFile = A.messageFile
  }
}
```

FYI there is an open discussion about how better to do imports here: https://github.com/openwdl/wdl/issues/214

**Comment by Welliton309** [comment] 2018-06-01 13:26
Thank you @patmagee for the recommendation. I think your solution is better than I proposed. However, the problem is how to reuse third-party workflows (as I mentioned) without changing them.

For example, it is not possible to change [this parameter](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.hg38.wgs.inputs.json#L12) in a workflow that calls this sub-workflow.

**Comment by patmagee** [comment] 2018-06-01 14:35
ah yes, @cjllanwarne wdyt?

**Comment by geoffjentry** [comment] 2018-06-04 21:30
As more of a meta-comment, I agree with @Welliton309 that keeping in mind reuse & composability is key, regardless of the actual implementation

**Comment by cjllanwarne** [comment] 2018-06-05 15:44
I used to be pretty against this sort of thing since it forever forces `sub.B` to be a workflow (ie it can never be refactored into a task without breaking everything that calls it)

... but sometimes it really is the best way to structure things and sometimes you want to import a WDL which has been written like this. So I'm moving more and more towards a "allow this sort of thing but continue to discourage omitting passthrough workflow inputs" stance (eg via IDE nagging).

IMO this sort of change should go hand in hand with something in the inputs file like @ruchim's https://github.com/openwdl/wdl/pull/192/files

**Comment by patmagee** [comment] 2018-06-07 12:12
I feel like we will need to allow declaring inputs called from a subworkflow like the following:

```wdl
workflow C {
  call sub.B {
    input:
      A.message = "Hello, World!"
  }
}
```

In retrospect, it seems like it would be what a user would naturally expect the naming convention to be for undeclared task inputs of a sub-workflow. 

@cjllanwarne The one thing that I start to see as potentially causing namespace clashes, is the name of the completed task/workfow wihtout aliasing. The above task for example will now become accessible at `B` instead of at `sub.B`. This is fine in the general case, but can lead to naming collisions if there is a task named `B` in the current WDL or another WDL thats being imported. Aliasing the call would get rid of this, but IMO we need a way keep things in their proper `scope`/`namespace`

**Comment by illusional** [comment] 2019-04-13 06:20
My opinion is you would have to use a call alias, saves the potential namespace clashes and allows you to call the same task multiple times.

**Comment by freeseek** [comment] 2020-09-15 21:47
I have the same exact issue as @wdesouza as I am trying to run the [processing-for-variant-discovery-gatk4.wdl](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl) as a sub-workflow and I don't know how to input the following variables:
```
SamToFastqAndBwaMem.ref_alt
SamToFastqAndBwaMem.ref_sa
SamToFastqAndBwaMem.ref_amb
SamToFastqAndBwaMem.ref_bwt
SamToFastqAndBwaMem.ref_ann
SamToFastqAndBwaMem.ref_pac
```
From the workflow into the subworkflow. If this is not possible, it would be nice to explicitly say so.

**Comment by jdidion** [comment] 2021-02-22 15:10
I believe this is addressed by `unsatisfiedTaskInputs` https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#computing-call-inputs. If so, please close.

**Closed by jdidion** 2021-02-22 15:10 UTC
