### ISSUE TITLE
What character encoding can be accepted to write WDL?

### ISSUE THREAD

**Issue by manabuishii** [openwdl/wdl#179] opened 2018-01-16 16:24 UTC
I look at [this](https://software.broadinstitute.org/wdl/documentation/spec) .
But I can not find any information about accepted character encoding to write WDL.
(  UTF-8 ??? )

**Comment by patmagee** [comment] 2018-01-25 02:58
duplicate of #165

**Closed by patmagee** 2018-01-25 02:58 UTC
